export const allowedMediaSourceHosts = [
    'youtu.be',
    'youtube.com',
    'www.youtu.be',
    'www.youtube.com',
    'twitch.tv',
    'www.twitch.tv',
    //'soundcloud.com',
    //'vimeo.com',
    //'archive.org',
    // 'dailymotion.com',
    // 'twitter.com',
    // 'reddit.com',
    // 'vk.ru',
];