version: '3.7'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - local

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.forCompose
    ports:
      - '3000:3000'
      - '3001:3001'
    links:
      - db
    depends_on:
      - db
    restart: always
    networks:
      - local

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      SYNK_API_URL: '${SYNK_API_URL:-http://localhost:3000}'
    ports:
      - 8080:8080
      - 80:80
      - 443:443

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: boss@synk.tv
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - local

networks:
  local:
    driver: bridge
