version: "3.7"

services:

  synk-db:
    build: 
      context: ./synk-db
      dockerfile: Dockerfile
    image: postgres
    networks:
      - local

  synk-api:
    build: 
        context: ./synk-api
        dockerfile: ./prod.Dockerfile
    ports: 
      - 3000:3000
    links:
      - synk-db
    depends_on: 
      - synk-db
    restart: always
    networks:
      - local

  synk-client:
    build: 
        context: ./synk-client
        dockerfile: ./Dockerfile
    environment: 
      SYNK_API_URL: "${SYNK_API_URL:-http://localhost:3000}"
    ports:
      - 8080:8080
      - 80:80
      - 443:443

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - synk-db
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: boss@synk.tv
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - local


networks:
  local:
    driver: bridge


