export const CUSTOM_EMOJIS = [
  {
    name: 'skadinod',
    shortNames: ['skadinod'],
    text: '',
    emoticons: [],
    keywords: ['skadi', 'nod'],
    imageUrl: 'https://media.tenor.com/UDaDt1XToTYAAAAi/skadi-nod-skadi.gif',
  },
  {
    name: 'pepe thinks',
    shortNames: ['pepe_think'],
    text: '',
    emoticons: [],
    keywords: ['pepe', 'think'],
    imageUrl: 'https://media.tenor.com/YAUMFOCgUu4AAAAj/think.gif',
  },
  {
    name: 'padoru',
    shortNames: ['padoru'],
    text: '',
    emoticons: [],
    keywords: ['padoru', 'xmas'],
    imageUrl: 'https://media.tenor.com/1cUMUU2xtgcAAAAi/padoru.gif',
  },
  {
    name:"abreadcutestealr",
    shortNames:["abreadcutestealr"],
    text: "",
    emoticons:[],
    keywords:["abreadcutestealr"],
    imageUrl: 'assets/emotes/abreadcutestealr.GIF' },
  {
    name:"cbnekodies",
    shortNames:["cbnekodies"],
    text: "",
    emoticons:[],
    keywords:["cbnekodies"],
    imageUrl: 'assets/emotes/cbnekodies.GIF' },
  {
    name:"dancin36",
    shortNames:["dancin36"],
    text: "",
    emoticons:[],
    keywords:["dancin36"],
    imageUrl: 'assets/emotes/dancin36.GIF' },
  {
    name:"hlhxhpitouwag98",
    shortNames:["hlhxhpitouwag98"],
    text: "",
    emoticons:[],
    keywords:["hlhxhpitouwag98"],
    imageUrl: 'assets/emotes/hlhxhpitouwag98.GIF' },
  {
    name:"kokominaughty",
    shortNames:["kokominaughty"],
    text: "",
    emoticons:[],
    keywords:["kokominaughty"],
    imageUrl: 'assets/emotes/kokominaughty.GIF' },
  {
    name:"smack59",
    shortNames:["smack59"],
    text: "",
    emoticons:[],
    keywords:["smack59"],
    imageUrl: 'assets/emotes/smack59.GIF' },
  {
    name:"zfumando",
    shortNames:["zfumando"],
    text: "",
    emoticons:[],
    keywords:["zfumando"],
    imageUrl: 'assets/emotes/zfumando.GIF' },

  {
    name:"animerave2",
    shortNames:["animerave2"],
    text: "",
    emoticons:[],
    keywords:["animerave2"],
    imageUrl: 'assets/emotes/animerave2.GIF' },
  {
    name:"cum77",
    shortNames:["cum77"],
    text: "",
    emoticons:[],
    keywords:["cum77"],
    imageUrl: 'assets/emotes/cum77.GIF' },
  {
    name:"fgfofo623",
    shortNames:["fgfofo623"],
    text: "",
    emoticons:[],
    keywords:["fgfofo623"],
    imageUrl: 'assets/emotes/fgfofo623.GIF' },
  {
    name:"isekaimangashake",
    shortNames:["isekaimangashake"],
    text: "",
    emoticons:[],
    keywords:["isekaimangashake"],
    imageUrl: 'assets/emotes/isekaimangashake.GIF' },
  {
    name:"milfsreacttrance",
    shortNames:["milfsreacttrance"],
    text: "",
    emoticons:[],
    keywords:["milfsreacttrance"],
    imageUrl: 'assets/emotes/milfsreacttrance.GIF' },
  {
    name:"wendytailwag56",
    shortNames:["wendytailwag56"],
    text: "",
    emoticons:[],
    keywords:["wendytailwag56"],
    imageUrl: 'assets/emotes/wendytailwag56.GIF' },

  {
    name:"Anime",
    shortNames:["Anime"],
    text: "",
    emoticons:[],
    keywords:["Anime"],
    imageUrl: 'assets/emotes/Anime.gif' },
  {
    name:"animeputaca",
    shortNames:["animeputaca"],
    text: "",
    emoticons:[],
    keywords:["animeputaca"],
    imageUrl: 'assets/emotes/animeputaca.gif' },
  {
    name:"gurahmm",
    shortNames:["gurahmm"],
    text: "",
    emoticons:[],
    keywords:["gurahmm"],
    imageUrl: 'assets/emotes/gurahmm.gif' },
  {
    name:"tbhrikkadance",
    shortNames:["tbhrikkadance"],
    text: "",
    emoticons:[],
    keywords:["tbhrikkadance"],
    imageUrl: 'assets/emotes/tbhrikkadance.gif' },
];
