
import { IconDefinition } from '@ant-design/icons-angular';

import {
    CrownOutline,
    BugOutline,
    MehFill,
    SmileFill,
    LoginOutline,
    ApiFill,
    MenuOutline,
    SwapOutline,
    FrownOutline,
    DeleteFill,
    EllipsisOutline,
    TeamOutline,
    TagFill,
    UserOutline,
    LockFill,
    NotificationFill,
    SyncOutline,
    RightOutline,
    InteractionFill,
    ShopFill,
    LoadingOutline,
    ForwardFill,
    PlayCircleOutline,
    CaretRightFill,

} from '@ant-design/icons-angular/icons';

export const NZ_ICONS: IconDefinition[] = [CrownOutline,
    BugOutline,
    MehFill,
    SmileFill,
    LoginOutline,
    ApiFill,
    MenuOutline,
    SwapOutline,
    FrownOutline,
    DeleteFill,
    EllipsisOutline,
    TeamOutline,
    TagFill,
    UserOutline,
    LockFill,
    NotificationFill,
    SyncOutline,
    RightOutline,
    InteractionFill,
    ShopFill,
    LoadingOutline,
    ForwardFill,
    PlayCircleOutline,
    CaretRightFill,
];