
import { IconDefinition } from '@ant-design/icons-angular';

import {
    ExperimentFill,
    DashboardOutline,
    CompassOutline,
    CrownOutline,
    BugOutline,
    MehFill,
    SmileFill,
    SmileOutline,
    LoginOutline,
    ApiOutline,
    MenuOutline,
    SwapOutline,
    FrownOutline,
    DeleteOutline,
    EllipsisOutline,
    TeamOutline,
    TagFill,
    UserOutline,
    LockOutline,
    NotificationFill,
    SyncOutline,
    RightOutline,
    InteractionOutline,
    ShopOutline,
    LoadingOutline,
    ForwardOutline,
    PlayCircleOutline,
    CaretRightFill,
    VideoCameraOutline,
    TagOutline
} from '@ant-design/icons-angular/icons';

export const NZ_ICONS: IconDefinition[] = [
    ExperimentFill,
    DashboardOutline,
    CompassOutline,
    CrownOutline,
    BugOutline,
    MehFill,
    SmileFill,
    SmileOutline,
    LoginOutline,
    ApiOutline,
    MenuOutline,
    SwapOutline,
    FrownOutline,
    DeleteOutline,
    EllipsisOutline,
    TeamOutline,
    TagFill,
    UserOutline,
    LockOutline,
    NotificationFill,
    SyncOutline,
    RightOutline,
    InteractionOutline,
    ShopOutline,
    LoadingOutline,
    ForwardOutline,
    PlayCircleOutline,
    CaretRightFill,
    VideoCameraOutline,
    TagOutline
];