# This workflow will execute for pull requests
# a clean installation of node dependencies using Yarn
# cache/restore them
# build the source code of client and api
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build client & API

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install client deps
      working-directory: synk-client
      run: yarn
    - name: Install API deps
      working-directory: synk-api
      run: yarn
    - name: Build client
      working-directory: synk-client
      run: npm run build
    - name: Build API
      working-directory: synk-api
      run: npm run build
