  name: Release

  on:
    push:
      tags:
        - '*'
      branches: [ master, tech/gh-release-action ]

  jobs:
    build_release:
      name: build_release
      runs-on: ubuntu-latest
      steps:
        
        - uses: actions/checkout@v3
        
        - name: Read version from API package.json
          id: set_version
          run: |
            content=`cat ./synk-api/package.json`
            # the following lines are only required for multi line json
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            version="${{fromJson(content).version}}"
            echo "::set-output name=version::$version"
        - name: Print version
          run: |
            echo "${{ steps.set_version.outputs.version }}"      
        
        - name: Setup Node.js version ${{ matrix.node-version }} and Yarn
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
        
        - name: Install client dependencies
          working-directory: synk-client
          run: yarn
        
        - name: Install API dependencies
          working-directory: synk-api
          run: yarn
        
        - name: Build client
          working-directory: synk-client
          run: npm run build
        
        - name: Replace URLs http to https in client artifacts
          working-directory: synk-client/dist/synk-client
          run: sed -i -- 's,http://www.youtube.com/iframe_api,https://www.youtube.com/iframe_api,g' *js
        
        - name: Build API
          working-directory: synk-api
          run: npm run build   
        
        ### PUT READ VERSION STEP BACK HERE
        
        - name: Determine build number
          id: set_build_number
          run: |
            dateNow=`$(date +%s)`
            content="${steps.set_version.outputs.version}.${dateNow}"
            echo "::set-output name=build_num::$content"
         
        - name: Print build number
          run: |
            echo "${{ steps.set_version.outputs.build_num }}"
            
        - name: Make ZIP of API and client artifacts 
          uses: papeloto/action-zip@v1
          with: 
            files: ./synk-client/dist/synk-client/ ./synk-api/dist/
            dest: release.zip

      #  - name: Release ZIP of client and API artifacts
      #    uses: ncipollo/release-action@v1
      #    with:
      #      artifacts: "release.zip"
      #      token: ${{ secrets.GITHUB_TOKEN }}

